export const members = [
  {
    id: 1,
    first_name: 'John',
    middle_name: 'Robert',
    last_name: 'Smith',
    preferred_name: 'Johnny',
    suffix: null,
    title: 'Rev.',
    gender: 'male',
    date_of_birth: '1965-04-12',
    marital_status: 'married',
    photo_url: 'https://example.com/photos/john-smith.jpg',
    phone_number: '555-0101',
  },
  {
    id: 2,
    first_name: 'John',
    middle_name: null,
    last_name: 'Smith',
    preferred_name: null,
    suffix: 'Jr.',
    title: null,
    gender: 'male',
    date_of_birth: '1991-09-30',
    marital_status: 'single',
    photo_url: null,
    phone_number: '555-0102',
  },
  {
    id: 3,
    first_name: 'Jane',
    middle_name: 'Marie',
    last_name: 'Smith',
    preferred_name: 'Janey',
    suffix: null,
    title: 'Mrs.',
    gender: 'female',
    date_of_birth: null,
    marital_status: 'married',
    photo_url: null,
    phone_number: '555-0103',
  },
  {
    id: 4,
    first_name: 'Maria',
    middle_name: null,
    last_name: 'Garcia',
    preferred_name: null,
    suffix: null,
    title: null,
    gender: 'prefer_not_to_say',
    date_of_birth: '1978-11-02',
    marital_status: 'widowed',
    photo_url: 'https://example.com/photos/maria-garcia.jpg',
    phone_number: null,
  },
  {
    id: 5,
    first_name: 'David',
    middle_name: 'James',
    last_name: 'Brown',
    preferred_name: 'Dave',
    suffix: null,
    title: null,
    gender: 'male',
    date_of_birth: '2001-02-14',
    marital_status: 'single',
    photo_url: null,
    phone_number: '555-0104',
  },
  {
    id: 6,
    first_name: 'Ellen',
    middle_name: null,
    last_name: 'Okafor',
    preferred_name: null,
    suffix: null,
    title: 'Dr.',
    gender: 'female',
    date_of_birth: '1989-07-23',
    marital_status: 'divorced',
    photo_url: null,
    phone_number: '555-0105',
  },
  {
    id: 7,
    first_name: 'Samuel',
    middle_name: null,
    last_name: 'Peterson',
    preferred_name: 'Sam',
    suffix: null,
    title: null,
    gender: 'male',
    date_of_birth: '1958-12-05',
    marital_status: 'married',
    photo_url: null,
    phone_number: '555-0106',
  },
  {
    id: 8,
    first_name: 'Grace',
    middle_name: 'Anne',
    last_name: 'Kariuki',
    preferred_name: null,
    suffix: null,
    title: null,
    gender: 'female',
    date_of_birth: null,
    marital_status: 'prefer_not_to_say',
    photo_url: null,
    phone_number: '555-0107',
  },
]